### ISSUE TITLE
Translation feature doesn't work

### ISSUE THREAD

**Issue by narcolepticinsomniac** [henrypp/chromium#1]
I'm using ChromiumType=stable-codecs-nosync, and the built-in translation feature doesn't work. It says it's translating the page, but nothing happens.

**Comment by henrypp** [comment]
No sync:
- Google API key is undefined in this build.
- So Google services like Sync, Hotword, Translate, Now, Hangout do not work.
- You will not be able to log in with your Google account and synchronize your data.

**Comment by narcolepticinsomniac** [comment]
Oh, okay. I wasn't making that connection, but it makes sense. I'm really glad to be rid of all the rest of it, but I occasionally miss the translation function. Thanks for the explanation, and for sharing your work.
