### ISSUE TITLE
chrome://plugins page goes "Aw, Snap" in x86 build

### ISSUE THREAD

**Issue by uBlock-user** [henrypp/chromium#10]
Steps to Reproduce

1) Install the latest **lkgr** x86 bit build
2) Run Chromium and open `chrome://plugins` page
3) It will fail to load and will crash instantly like this - https://i.gyazo.com/ef264fe0700461a435121b82ae78521f.png

Browser Info

- Version v56.0.2906.0 r428695 (dev) sync

- Build type - LKGR

- Architecture - x86 build

PS - This doesn't happen in the latest x64 bit build, so the issue underlying is in the x86 build only.

**Comment by chrme** [comment]
new lkgr build will be today, maybe this issue is fixed..

**Comment by rjkpa** [comment]
Thanks, but can you reproduce it ?

**Comment by uBlock-user** [comment]
Thanks, but can you reproduce the issue I mentioned here ?

**Comment by chrme** [comment]
yeah, i can

**Comment by uBlock-user** [comment]
So is it fixed in the 32 bit build or is it for a later release ?

**Comment by chrme** [comment]
yes, it's fixed in 56.0.2916 win32

**Comment by uBlock-user** [comment]
Thanks, you may add the labels and then close this issue.
