### ISSUE TITLE
Error message at Release 49.0.2623.112-r403382-win32 in Win XP SP3

### ISSUE THREAD

**Issue by goodman3654** [henrypp/chromium#12]
double click chrome.exe and error occured.

"The procedure entry point CloseTouchInputHandle could not be located in the dynamic link library USER32.dll"

OS: Windows XP SP3

![image](https://cloud.githubusercontent.com/assets/10626700/20887724/d25df8f2-bb36-11e6-8658-4420cf2e0a8d.png)

any help?
thanks.

**Comment by chrme** [comment]
I don't know, i test this build on almost 60 different pc with windows xp sp3 and all works. Maybe you have different version of user32.dll? or doesn't update directX? or have some injection in system calls?

**Comment by goodman3654** [comment]
In my windows xp sp3, there is no such API "CloseTouchInputHandle" in export table of user32.dll.
user32.dll version is 5.1.2600.5512.

![image](https://cloud.githubusercontent.com/assets/10626700/20902805/bd8250e4-bb73-11e6-9511-9d11f0e798e6.png)

And I check msdn, It seems like XP doesn't support API "CloseTouchInputHandle". A little bit weird.

https://msdn.microsoft.com/zh-tw/library/windows/desktop/dd371423(v=vs.85).aspx
![image](https://cloud.githubusercontent.com/assets/10626700/20902981/92f5311a-bb74-11e6-82a0-eb5e99ef3483.png)

**Comment by uBlock-user** [comment]
Downgrade to Chrome 50, beggining with Chrome 51 Windows XP3 is phased out. So either get Windows 7 or later or downgrade to Chrome 50.

**Comment by chrme** [comment]
ok now i'm able to catch this error, i'll try to help you.

**Comment by chrme** [comment]
@goodman3654 try updated build https://github.com/henrypp/chromium/releases/tag/v49.0.2623.112-r403382-win32

**Comment by goodman3654** [comment]
![image](https://cloud.githubusercontent.com/assets/10626700/21470033/94f56e8e-cab1-11e6-94fa-6017aeb13751.png)

The error message was gone!! thanks a lot!

**Comment by chrme** [comment]
good! thanks for report!
