### ISSUE TITLE
Latest build issue

### ISSUE THREAD

**Issue by uBlock-user** [henrypp/chromium#16]
### Issue

The latest build leaves a closing and opening trail shadow when a tab is closed or opened.

### Screenshot

https://i.gyazo.com/56bb427beafa832443f95f2d4d52a9d7.png

Build - Version 57.0.2981.0 (64-bit) lkgr
OS - Win 10 x64

@chrme Also `chrome://plugins` is gone, what's up with that ?

**Comment by chrme** [comment]
@uBlock-user plugins page was officially removed - https://bugs.chromium.org/p/chromium/issues/detail?id=615738 :disappointed: 
about tabs: i can't reproduce it, but maybe it specify for some video cards, gotta check the issues list

**Comment by uBlock-user** [comment]
@chrme So how do you disable all the 4 plugins ?

**Comment by CHEF-KOCH** [comment]
I can confirm this bug with latest Chromium, rendering is broken. 

![kasqlq](https://cloud.githubusercontent.com/assets/727123/21943500/c56d01ba-d9d1-11e6-8698-582d348aece6.gif)

**Comment by chrme** [comment]
@uBlock-user i don't know, pdf plugin can be disabled in the settings now

**Comment by uBlock-user** [comment]
Chrome Dev version 57.0.2979.0 works fine. @chrme Does this happens in other non sync and 32 bit builds ? Yes I can disable pdf plugin, but what about Widevine and Native client plugin ? How to disable them ?

**Comment by chrme** [comment]
@uBlock-user can you try this build https://github.com/henrypp/chromium/releases/tag/test ?

> How to disable them ?
i think chromium authors disable this feature

**Comment by uBlock-user** [comment]
> @uBlock-user can you try this build https://github.com/henrypp/chromium/releases/tag/test ?

@chrme Same result - https://i.gyazo.com/4a4e0fabe7bb61b5886a63c1fbe38c4a.png 😞

**Comment by chrme** [comment]
seems like a bug in a code
also i just found this https://bugs.chromium.org/p/chromium/issues/detail?id=681314

**Comment by uBlock-user** [comment]
That confirms that's its the chromium bug. Possibly a rendering screw up by the team. Also it seems I cannot downgrade versions. Once installed 57.0.2981.0 and then remove it and install 57.0.2970.0 It won't let you install on the basis that you have a newer version installed. Some registry keys are not being removed which are causing this I suppose.

**Comment by chrme** [comment]
IIRC chromium stores data only in HKEY_CURRENT_USER\Software\Chromium
btw can you check the tab bug with a clean profile, just in case.

**Comment by uBlock-user** [comment]
I found keys in other places in registry too and I deleted them, still whenever I open Chromium 57.0.2970.0
 I get "Profile cannot be opened correctly" this started happening ever since I removed the latest and installed back the previous, which is really pissing me off, this is a whole another issue from the tab issue fyi.

> an you check the tab bug with a clean profile

Already did, deleted the Chromium folder after the latest build screw up and installed fresh build from releases page and still the same.

**Comment by uBlock-user** [comment]
All dev builds from `57.0.2981.0` onwards to the latest one are littered with this bug, stay on stable channel to avoid this.

**Comment by chrme** [comment]
here it is https://bugs.chromium.org/p/chromium/issues/detail?id=680901
and they fix it, so i'm doing a new build within 1-2 days

**Comment by uBlock-user** [comment]
Thanks for the heads up. I will await your release.

**Comment by chrme** [comment]
it's here https://github.com/henrypp/chromium/releases/tag/v57.0.2987.0-r444945-win64

**Comment by uBlock-user** [comment]
Works fine. Closing the issue.
