### ISSUE TITLE
Can you make a version 52 of chromium  with codec support? 

### ISSUE THREAD

**Issue by danid12** [henrypp/chromium#17]
The reason I ask version 52 
is because versions 53 and 54 have a known bug with SSL.
in version 55 you can't disable the terrible material design anymore. 
So version 52 is the last good chromium version.
can you please create it?
thanks

**Comment by uBlock-user** [comment]
https://github.com/henrypp/chromium/issues/5#issuecomment-249423988

It's version 55 and the last version where you can disable material design via chrome flags

**Comment by danid12** [comment]
I tried it. I disabled all flags related to martial design including of course the three you mentioned. 
But in v55.0.2883.87-r423768-win32: Update args_gn.md version it's not working, unfortunately.  

If it will be possible to create an older version 55, the last good version that should support material design it will be the best option.

**Comment by danid12** [comment]
so from the thread you linked too I understand that in the last version before v55.0.2867.0 
gave the option to disable material deign. So hope that this last version before v55.0.2867.0 can be compiled.
It will be very useful for many people
thanks 
@henrypp @chrme @uBlock-user

**Comment by danid12** [comment]
I checked  now Version 55.0.2866.0 (Win-419602-chrome-win32).
One of the latest versions that allow disabling material design. 
But it still has the SSL bug . 
And in this version you can't disable the annoying message of Secure/Not Secure.
It can be disabled only in newer versions.
so maybe after all 52 version is better ..
I hope I had the knowledge to do it by myself but i don't really understand programming.
So hope @chrme can make that version, it will be great.
thanks

**Comment by danid12** [comment]
Also 
v49.0.2623.112-r403382-win32
is very bugy.
it's crash every few minutes
and there is also a weird copy-paste bug i never saw in other chormium versions. 
so today there is no available version without a bugs and the crappy  changes google put in the never versions.
so version 52 with codec support is desperately needed.

**Comment by chrme** [comment]
well, i'll try to build it in 2-3 days, do you need win32 or x64?

**Comment by danid12** [comment]
@chrme  
win 32
thank you very much :)

**Comment by chrme** [comment]
it's [here](https://github.com/henrypp/chromium/releases/tag/v52.0.2743.120-r394939-win32)

**Comment by danid12** [comment]
It's perfect!!!!!!!!!
thank you very much @chrme
There are not enough words to describe how much I appreciate and thank you for the great job you have done. I believe I will use this version in the next years ...thanks a lot, you are awesome.

**Comment by B3bomber** [comment]
@chrme May I have a 64 bit of that one danid12 requested? I'm having issues (documented already too) with the current update henry++ has released.

Why isn't there an easy way to find older versions we can revert to when something breaks badly?

**Comment by chrme** [comment]
i'll try

**Comment by danid12** [comment]
@B3bomber 
You can see older versions when you click "releases" button in the main page of the project.
https://github.com/henrypp/chromium/releases

**Comment by chrme** [comment]
@B3bomber here is [win64](https://github.com/henrypp/chromium/releases/tag/v52.0.2743.120-r394939-win64)

**Comment by danid12** [comment]
I tried now the 64 bit version, it is very good, thanks.
When you asked me, I told you I prefer the 32 bit version, Although I use a 64 bit windows
because in the past chromium 32 bit version worked faster when I made a comparison between the 32 and 64 versions ( I think it was in older computer), so I got used to the 32 bit version, but when I installed now the 64 bit version, I see it works smoother and faster, so I am very happy B3bomber asked you to create this version.

**Comment by B3bomber** [comment]
Thank you very much @chrme.

@danid12, happy to know it was an improvement for you. I try to use native support for apps when possible and in the case of chromium the 64 bit version is preferred.

**Comment by chrme** [comment]
good!
