### ISSUE TITLE
flash problem with nosync version

### ISSUE THREAD

**Issue by dkastrup** [henrypp/chromium#18]
Looks like opening any site featuring flash content causes a crash (aw snap) with the nosync version of Chromium. It has been like this for some time, but only today I tried the sync version. As a sample URL, you can use https://noticias.uol.com.br/

**Comment by uBlock-user** [comment]
It is happening since version 57 and was carried into version 58

**Comment by chrme** [comment]
Yeah, flash can only work with the sync version. Why? I don't know :smile: i'm not a chromium developer. I can only assume that it depends on webrtc somehow.

**Comment by uBlock-user** [comment]
Nik but why does it consume all my RAM and crash the browser itself ? Do you know anything about it ?

**Comment by chrme** [comment]
I'm also doesn't know why is this happen, and i don't change my build config from the beginning.. so i guess it's in the code

**Comment by uBlock-user** [comment]
Well, I'm done with Flash and only 7.2 % of the websites on the Internet are using flash, so I uninstalled it. Submitting a bug report to Chromium devs is a pain in the ass and waste of my time. This doesn't happen with HTML 5 player and Chromium runs fine on it, So screw flash.

**Comment by chrme** [comment]
then i close it :smile:
