### ISSUE TITLE
2 tunnels to Google ...

### ISSUE THREAD

**Issue by rmsEfx** [henrypp/chromium#2]
Thank you for your builds, Nik ... and Hello!!

Is it possible to make a clean builds of Chromium without any tunnels to Google .. just found 3: 2 opening at startup and one when "Settings" dialog is open? Just replacing Google address links with any indifferent text strings .

Thank you!

**Comment by Unrepentant-Atheist** [comment]
Yes, please. NO DATA FER U, GOOGLE! GIT OF ME LAWN!

**Comment by rmsEfx** [comment]
To this moment, Chromium opens 7 tunnels and it's no any page, opened in any tab:

translate.googleapis.com
clients1.google.com
clients2.google.com
mtalk.google.com
android.clients.google.com
googleads.g.doubleclick.net
stats.g.doubleclick.net

All of this addresses can be blocked in HOSTS file (if Chromium runs in Windows OS) .. and the only activity of Chromium, that will happen after blocking is the constant attempts to open clients1.google.com
