### ISSUE TITLE
err_ssl_protocol_error

### ISSUE THREAD

**Issue by narcolepticinsomniac** [henrypp/chromium#20]
I'm getting a lot of errors and content failing to load in stable-codecs-sync Version 56.0.2924.87 (64-bit). At first, I figured it might be an extension, or I had somehow screwed something up, so I did a completely separate install. Freshly installed with nothing added, I get the same issue. Then I thought it may be an OS level issue, so I downloaded Google Chrome (stable), and it has no problems. 

It occasionally happens for whole webpages, but a real noticeable example is any Google Image Search. More than half the images fail.
![chrome_2017-02-19_01-50-38](https://cloud.githubusercontent.com/assets/14100003/23100151/62952a30-f647-11e6-95c5-8db2436f64c4.png)
![chrome_2017-02-19_01-51-40](https://cloud.githubusercontent.com/assets/14100003/23100153/69bb1c70-f647-11e6-8abe-d90cafd550f9.png)

I switched over to the dev build and it has no issues either. I really prefer to use stable though.

**Comment by uBlock-user** [comment]
Offer a link and steps to reproduce.

I tried Google Images, works fine here.

**Comment by narcolepticinsomniac** [comment]
Appreciate the response. You testing in stable, not dev? I didn't think it necessary to provide a specific link since it happens on any image search, but:

https://www.google.com/search?q=gigi+hadid&espv=2&biw=1366&bih=672&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjOoPHR1ZvSAhVCbSYKHXaOAdwQiR4IngE

On a completely fresh install via chrlauncher, as soon as it opens the first time, I do that image search and get this:
![chrome_2017-02-19_02-48-19](https://cloud.githubusercontent.com/assets/14100003/23100438/74c53888-f64e-11e6-8df0-356e5dcf84e8.png)

As I mentioned, no issue with Google Chrome stable, or Chromium dev.

**Comment by narcolepticinsomniac** [comment]
Errors:
![chrome_2017-02-19_02-56-56](https://cloud.githubusercontent.com/assets/14100003/23100457/2517ea3c-f64f-11e6-9a90-494d494a25d6.png)

**Comment by uBlock-user** [comment]
I have tested in stable and I run both stable and dev.

I cannot reproduce it. 

![](https://i.gyazo.com/542ee467dccc3e8874d0224f9b59a7c2.png)

I suggest you use the archive version and see if you can still reproduce it.

**Comment by narcolepticinsomniac** [comment]
Alright, I tested that it might be even worse. I'm having trouble getting it to connect to Google via search at all (I tried a couple direct URLs like Reddit which worked):
![chrome_2017-02-19_03-19-07](https://cloud.githubusercontent.com/assets/14100003/23100557/595888c6-f652-11e6-91d3-d98e36309ec2.png)

Btw, Windows Diagnostics is as useless as ever. 

I got curious, so I tested the stable-codecs-sync I have on my entertainment center desktop hooked up to my TV. It has the same exact issue. Both different OS's (Win 8.1, Win 7).

**Comment by uBlock-user** [comment]
Try that - https://aboutssl.org/fix-google-chrome-error-err_ssl_protocol_error 

Also disable any activated features from `chrome://flags`

**Comment by narcolepticinsomniac** [comment]
Unfortunately, that is the exact page I referenced yesterday when attempting to troubleshoot. I followed every step and then some. Even stopped/restarted w32time via the command line.

I really do appreciate the effort. The fact that you can't repro is disappointing, but this update has been out for a little bit and I don't see anyone else complaining either.  Google Chrome and Chromium dev have no issues, which led me to believe that the Chromium stable build was somehow the culprit. Like I said I've now confirmed it on separate fresh installations on different computers/OS's. If this is just happening for mine, it can only be witchcraft.

**Comment by uBlock-user** [comment]
Did you try all the solutions listed on that page ?

Secondly, have you tried clearing all cache and site data ?

**Comment by chrme** [comment]
Can you check the dev tools (F12) -> Security -> hit F5 on that page with error (check the overview, check the certificate)..
Maybe someone (ISP, local admin) is intercept your encrypted traffic?

**Comment by narcolepticinsomniac** [comment]
> Did you try all the solutions listed on that page ? Secondly, have you tried clearing all cache and site data ?

Yes everything on that page and other things I found elsewhere. Of course, one of the first things I tried was clearing history/cache and I've been doing it right along, but this is happening immediately after brand new installations. No extensions, history, cache, nothing.

> Can you check the dev tools (F12) -> Security -> hit F5 on that page with error (check the overview, check the certificate)..

I checked out the security tab, and it's saying gstatic.com is "unknown & canceled".
![chrome_2017-02-19_07-37-09](https://cloud.githubusercontent.com/assets/14100003/23102500/81c35bda-f678-11e6-9e4c-c2c6a53c29d3.png)



> Maybe someone (ISP, local admin) is intercept your encrypted traffic?

I'm sounding like a broken record here, but every browser (Chrome stable, Chromium dev, Firefox) works fine except for stable-codecs-sync. It's borked right out of the box upon installation. I've installed it through chrlauncher, and the archived version. Same problem on 2 different computers and OS's. 

I'm baffled truthfully. I gotta take off for work, but I'd appreciate any advice you can give, which I will try when I get back. Thanks.

**Comment by uBlock-user** [comment]
> I'm baffled

So am I. As I see it, you have limited options. Either you investigate, find the root cause and fix it yourself, or use Google Chrome for the time and await release of version of 57 which will happen in March or use Chromium Dev.

**Comment by narcolepticinsomniac** [comment]
Well, at least I'm [not the only one](https://chromium.woolyss.com#comment-1876), not that I'd wish this on anybody. As that comment states, I most frequently notice Google content being blocked. I swear I've tried every solution I could find on the internet. I also tried the suggestions that followed in that thread. The flag mentioned doesn't work, and updating components doesn't seem to successfully update anything. I even tried installing SRWare Iron as a stopgap, but it has the same bug. It appears to be present in all v56 releases. Why it doesn't affect everyone is a mystery.

I've been trying to use dev, but it isn't very stable.  I refuse to break down and go back to Chrome, even though somehow or another they've sprinkled enough black magic on theirs, that even though it's the same version, their stable isn't affected. 

I tested a few of the releases. The newest/oldest v58 both had different little bugs. I finally settled on [the last v57](https://github.com/henrypp/chromium/releases/tag/v57.0.2987.0-r444945-win64). It's the closest to an official beta release AFIK, and it seems pretty stable comparatively.

It'd be nice if official beta releases were an option, but maybe there's not enough demand to be worth the effort.

I have a couple questions regarding releases/non-chrlauncher installations, since I'm not familiar. Why are even the most recent dev builds marked "chrme released this on Dec 24, 2016"? Seems inaccurate, but what do I know? Also, why is the `chrome://plugins` page missing from the v57 "semi-portable" zip install I did. They seem to work fine, but the page is absent.

**Comment by uBlock-user** [comment]
`chrome://plugins` page has been officially removed as of v57. You can google about it and you will find many articles.

> It'd be nice if official beta releases were an option, but maybe there's not enough demand to be worth the effort.

Ask Nik if he's interested in compiling Beta releases, then you're in luck.

**Comment by chrme** [comment]
@narcolepticinsomniac 
1) "Dec 24, 2016" is my last commit to the repository, i don't know how to change it to the latest upload date (but if you open it through [**API-URL**](https://api.github.com/repos/henrypp/chromium/releases) you can see *published_at* date and it's ordered by date)
2) sorry but can't build the beta, it's just too much for my PC :smile: (but if you want to use the beta why not try the lkgr? i'm using the lkgr all the time as my primary browser and also many users)
3) are you check these google site through proxy or tor? maybe it's your IP address somehow? :confused:

**Comment by uBlock-user** [comment]
Add this flag and see if it work - `--ignore-certificate-errors`

**Comment by narcolepticinsomniac** [comment]
Nah, I saw that in the woolys thread. Not only does it throw an annoying inline security warning, but it doesn't work for this particular issue either.

I am happy to report though, that after a ridiculous amount of time wasted, I finally came across a pretty simple solution. I found it in a Raspberry Pi forum, of all places. There's quite a few users affected judging from reports, if you limit searches to the last couple weeks. Anyway, flipping a simple flag does the trick.

Go to: chrome://flags/#ssl-version-max

and set it to "TLS 1.2".

A little less secure, I'm sure, but you'll have an actual functioning Chromium stable. Whatever voo-doo is causing this bug seems to be fixed somewhere in the v57's, so just remember to flip it back down the road.

Hopefully this saves someone else the time and aggravation. Thanks to everyone here for the assistance.

**Comment by uBlock-user** [comment]
Quite surprising, I'm using `TLS 1.3` in 56 and 58 both.

**Comment by chrme** [comment]
yeah, this is a mystery indeed :confused: 
anyway thanks for the solution!

**Comment by superbob** [comment]
BTW, there's a bug filled in bugs.chromium.org: [693943](https://bugs.chromium.org/p/chromium/issues/detail?id=693943). It was fixed yesterday in commit [96d085c](https://chromium.googlesource.com/chromium/src.git/+/96d085c8adbd2092696fdc6c622d61a23d5de0bf).
