### ISSUE TITLE
Large number of out of memory errors while watching Twitch streams

### ISSUE THREAD

**Issue by NEXUS2345** [henrypp/chromium#22]
While watching any Twitch stream, about 20-30 mins in, the page always crashes, complaining it is out of memory. I have 32GB of RAM, so it definitely isn't the system.

Version is latest 64-bit with sync.

**Comment by NEXUS2345** [comment]
Apologies, appears I was using build 3060 instead of 3067. Will reopen if issue recurs.

**Comment by uBlock-user** [comment]
That's probably the flash player issue, it doesn't happen if you uninstall the flash player.
