### ISSUE TITLE
Chromium x64/86 latest archive build crashes

### ISSUE THREAD

**Issue by uBlock-user** [henrypp/chromium#23]
Steps to Reproduce

1) Install the archive version of the latest dev build of x64 category or x86 and pick the sync version
2) Open Chrome.exe
3) Get crashed

![](http://i.imgur.com/I5IErQK.png)

@chrme Can you reproduce it nik ?

**Comment by uBlock-user** [comment]
I have searched for current "crash" cases at the bug tracker - https://bugs.chromium.org/p/chromium/issues/list?can=2&q=OS%3D%22Windows%22+crash&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids

@chrme Can you tell me which one applies to this one ?

**Comment by chrme** [comment]
i've checked on 3 different PCs and all work fine.. but i don't have a win10 anywhere (only win7) so maybe it's due to this? :confused:

**Comment by uBlock-user** [comment]
Well it's crashing just by opening chrome and I don't have windows 7, so I cannot confirm that.

**Comment by chrme** [comment]
@uBlock-user yeah, i've checked it on win10 and there is a crash on startup..

**Comment by uBlock-user** [comment]
@chrme, No, I meant from the bug tracker which I posted in https://github.com/henrypp/chromium/issues/23#issuecomment-299718391

Have you checked that out ?

**Comment by uBlock-user** [comment]
Filed an official bug report - https://bugs.chromium.org/p/chromium/issues/detail?id=719402

**Comment by uBlock-user** [comment]
@chrme Seems to have been fixed in `Version 60.0.3094.0 (Developer Build) (64-bit)` You may compile a new release on this build or later builds

**Comment by chrme** [comment]
ok, i'll check it

**Comment by uBlock-user** [comment]
Let me know when you release a new build.

**Comment by chrme** [comment]
i've build the revision

 [469963](https://chromium.googlesource.com/chromium/src/+/0cd83681ad239907cf6fc7c07cfcca1262474529) and nothing changed, there is still a crash on startup

**Comment by uBlock-user** [comment]
Did you use the version 60.0.3094.0 source for building it ? That doesn't crash for me.

**Comment by uBlock-user** [comment]
@chrme 469905 works perfectly, use that!

**Comment by uBlock-user** [comment]
Version 60.0.3096.0 works fine as expected, closing the issue.
