### ISSUE TITLE
Regression bug

### ISSUE THREAD

**Issue by uBlock-user** [henrypp/chromium#24]
Broken rendering of extension popups, padlock info window etc.

![](https://i.gyazo.com/d463a58d8a832ba3a96be80626fafa1d.png)

@chrme version 60.0.3099.0 64-bit sync

**Comment by uBlock-user** [comment]
![](http://i.imgur.com/8mmdvPL.png)

**Comment by uBlock-user** [comment]
Filed a bug at https://bugs.chromium.org/p/chromium/issues/detail?id=722091

**Comment by uBlock-user** [comment]
@chrme Are you there or what ?

**Comment by uBlock-user** [comment]
@chrme Would you try 60.0.3100.0 and do what he says here - https://bugs.chromium.org/p/chromium/issues/detail?id=722091#c2

**Comment by chrme** [comment]
@uBlock-user Hi! Just've read your issue on chromium.org and run the 3099 build on a virtual pc (win10) but cannot catch this bug :disappointed: 
The temp solution is downgrade to the build 3096 i guess. I'm going to compile next build in a few days (~3106 build)

**Comment by uBlock-user** [comment]
@chrme The question is will your next build still have this bug and the worst part is I'm the only one who can reproduce it!!!

**Comment by chrme** [comment]
@uBlock-user i don't know :disappointed_relieved: 
my build config is unchanged for a long time, the only suspect is sources..

**Comment by uBlock-user** [comment]
@chrme They cannot reproduce it either, so I'm really fucked 😞

**Comment by verlain3** [comment]
All fine here with 60.0.3099.0 no-sync x64

**Comment by uBlock-user** [comment]
Mine's all on sync

**Comment by uBlock-user** [comment]
A similar bug has appeared  - https://bugs.chromium.org/p/chromium/issues/detail?id=724450

Looks like I'm not the only one.

**Comment by chrme** [comment]
@uBlock-user is [THIS](https://bugs.chromium.org/p/chromium/issues/detail?id=724367) issue related to your?

**Comment by uBlock-user** [comment]
Yeah could be, flickering does happen on my side.

**Comment by chrme** [comment]
@uBlock-user yeah, in a few hours i'll start compile

**Comment by uBlock-user** [comment]
@chrme Gonna try the latest compiled build, wait for my feedback.

**Comment by uBlock-user** [comment]
Still happens in 64 bit 😞

**Comment by chrme** [comment]
:fearful: damn, and recent officials build also?

**Comment by uBlock-user** [comment]
Yes the most recent official builds tested from here - https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/473414/chrome-win32.zip

Looks like I'm gonna stay stuck with this one for a long time 😨

**Comment by chrme** [comment]
can you try [this release](https://github.com/henrypp/chromium/releases/download/test/chromium_x64_60.0.3105.0.7z) ?

**Comment by uBlock-user** [comment]
can't download it, terribly slow speed, upload on google or zippyshare please!

**Comment by chrme** [comment]
@uBlock-user this issue stay in incognito mode?

**Comment by uBlock-user** [comment]
@chrme Yes this issue also happens in incognito mode also

**Comment by uBlock-user** [comment]
@chrme Try compiling this one -
 https://chromium.googlesource.com/chromium/src/+/3cb12d3b5ec5f5b0b4cc850e4cedefdad40f925f

I can no longer reproduce that bug in that build

**Comment by chrme** [comment]
@uBlock-user good, but LKCR still on r473419, so tomorrow i think it'll reach r473456 and then i compile it

**Comment by uBlock-user** [comment]
@chrme But aren't you compiling LKGR releases instead of LKCR ?

**Comment by chrme** [comment]
no, lkgr soon will be dropped (and it's updated rarely), i switch to lkcr a couple of months already

**Comment by uBlock-user** [comment]
@chrme that's why we're having such issues so randomly, you should switch to a stable build compared to lkcr, otherwise these incidents will continue to happen.

**Comment by chrme** [comment]
yeah, but there is a [problem](https://bugs.chromium.org/p/chromium/issues/detail?id=407399)

**Comment by uBlock-user** [comment]
It's been there for the past 3 years dude! It's not gonna happen, check the status, it says `Available` and hasn't changed and won't for a long long time.

**Comment by uBlock-user** [comment]
Current Dev build is 60.0.3107.4, so compile that.

**Comment by uBlock-user** [comment]
@chrme Here we go again - https://i.gyazo.com/618587e05dfa4d8886f4c2d7632067d1.mp4

This is why I told you to NOT to compile bleeding edge builds, they're all broken as fuck!

**Comment by verlain3** [comment]
So you have your GPU drivers updates? @uBlock-user

**Comment by uBlock-user** [comment]
@verlain3 To answer your question, yes all are up-to-date, however GPU drivers are irrelevant at this stage as this is affecting others too[1] and something in Chromium lately is broken specifically one or UI components.

[1]https://github.com/gorhill/uMatrix/issues/788

**Comment by chrme** [comment]
@uBlock-user then you must certainly use version 60.0.3096.0, because LKGR is still on 3094 build

**Comment by uBlock-user** [comment]
@chrme I'm rather stuck with that. What about you ? Can you not reproduce it ?

**Comment by chrme** [comment]
@uBlock-user no, i've tried 4 different pc's

**Comment by uBlock-user** [comment]
on which OS ?

**Comment by chrme** [comment]
@uBlock-user win7 and win10

**Comment by uBlock-user** [comment]
Wait a min, so it only happens if you disable Hardware Acceleration ? I always have that disabled by default.

**Comment by chrme** [comment]
@uBlock-user i have disabled HWaccel from time to time, but now it's enabled

**Comment by uBlock-user** [comment]
@chrme Yes are you sure it only happens if you disable H/W Acc. ?

**Comment by verlain3** [comment]
Can confirm. 
If you disable Hardware Acceleration that happens. That's why it didn't for me because i always had it enabled.

**Comment by uBlock-user** [comment]
I will file another bug. Thanks for checking it out @verlain3

**Comment by uBlock-user** [comment]
New bug report - https://bugs.chromium.org/p/chromium/issues/detail?id=726974

**Comment by uBlock-user** [comment]
As expected, the bug is still present in the latest build, I guess we're in wait for the long haul.

**Comment by chrme** [comment]
i think so

**Comment by uBlock-user** [comment]
Issue has been merged into  - https://bugs.chromium.org/p/chromium/issues/detail?id=720105

A fix is in progress.

**Comment by uBlock-user** [comment]
@chrme They have landed the fix in v61 - https://bugs.chromium.org/p/chromium/issues/detail?id=726974#c14

Can you check the revision of the revision and then compile it ?

**Comment by uBlock-user** [comment]
This is the latest LKCR commit - https://chromium.googlesource.com/chromium/src/+/refs/heads/lkcr

Not sure if the fix was landed before this commit.

**Comment by verlain3** [comment]
I tested last rob's build 61.0.3125.0 (478007) and this problem is fixed. 
The bookmarks favicon is still cut off though

**Comment by uBlock-user** [comment]
@chrme Thanks the bug has been fixed in your latest build and I can longer reproduce it. Consider this patched. 

> The bookmarks favicon is still cut off though

I don't see it cut off, appears as expected.

**Comment by verlain3** [comment]
> I don't see it cut off, appears as expected.

They appear cut off for me. Also: https://chromium.woolyss.com/#comment-2113

**Comment by uBlock-user** [comment]
Well I can't reproduce it. I added 7 bookmarks and all of them have their favicon, none appears to be cutoff, sounds like a rare condition.
