### ISSUE TITLE
Next time you'll build "stable-codecs-nosync"...

### ISSUE THREAD

**Issue by pluto439** [henrypp/chromium#27]
...can you also upload object files?

I'd like to play with source code a bit, but don't want to recompile everything.

**Comment by chrme** [comment]
Wait what? I can't because the size of this files is ~15gb! :smile:

**Comment by pluto439** [comment]
Holy shit, why it's so big? I thought object files should be at around the same size as the executable, 200 mb.

Well, I expected something like that. Never mind then.

**Comment by uBlock-user** [comment]
The whole Chromium source code takes around 60 GB on WPO builds and around 150 GB without WPO optimisation. Uploading is impossible on github as the size of the repo for free plansis limited to 1 GB.
