### ISSUE TITLE
grid-area : Unknown property name

### ISSUE THREAD

**Issue by jfpicard123** [henrypp/chromium#28]
Hi!

Since version 56, we're getting "Unknown property name" for the grid-area property .. Is that a bug? How do we work this around?

Thanks!

**Comment by chrme** [comment]
please show the example, because css grid-area is working fine for me

**Comment by jfpicard123** [comment]
Attached screenshot + version info. Please note that it shows fine in Chrome. Not in Chromium.

Ideas?

[grid-area.docx](https://github.com/henrypp/chromium/files/1382471/grid-area.docx)

**Comment by jfpicard123** [comment]
And please, let me add this detail : it's not since v56 .. I've seen the same behavior in all versions of Chromium I tested (54-32b, 56-32b, 56-64b, 63-32b)
