### ISSUE TITLE
No PPAPI Flash plug-in auto-detection ...

### ISSUE THREAD

**Issue by rmsEfx** [henrypp/chromium#3]
Since version 23.0.0.126 of Adobe Flash player (PPAPI, Adobe Labs, Beta's) it's no automatic detection of a plug-in from Adobe. Version 23.0.0.111 detects without any problem ...

Is it an issue to Adobe, Chromium's crew or to this build ... ?

Chromium version 54.0.2823.0 (64-bit) (Win7 pro, 64-bit)

**Comment by rmsEfx** [comment]
Plug-in is installed but there is no any record in chrome://plugins/ and chrome://flash/

**Comment by madreason** [comment]
You can set plugin path and version like this:
`chrome.exe --ppapi-flash-path="pepflashplayer.dll" --ppapi-flash-version="18.0.0.160" --allow-outdated-plugins`

**Comment by rmsEfx** [comment]
Thank you for the answer ... it solve the situation
