### ISSUE TITLE
Getting popup in password field even though "Manage Password" is disabled

### ISSUE THREAD

**Issue by onmyouji** [henrypp/chromium#30]
Hello,

Why does the browser give me this popup in every password field? Never have this problem on Chrome.
![asepsm](https://user-images.githubusercontent.com/8424198/33520953-50f781d2-d7f7-11e7-9b63-2af76d669b35.png)

I've already disabled Auto-fill and "Manage Password" in settings. 
Just installed this Chromium, never saved any password, the password list is empty. 
Tried "Clear browsing data" and reinstall, also tried to use Incognito mode, still get the popup.

I'm running Stable x64 Nik NoSync build on Windows 10 x64.

**Comment by onmyouji** [comment]
Someone from the website told me to disable this flag, it solved the problem.
chrome://flags/#enable-manual-fallbacks-filling

But I don't have this problem on Chrome. I checked the flag in Chrome, it's default, I don't need to disable anything in Chrome.

**Comment by uBlock-user** [comment]
Value set for Chromium must be different then.
