### ISSUE TITLE
Virus detected in Installer

### ISSUE THREAD

**Issue by ramones79** [henrypp/chromium#34]
AVIRA Anti-virus detects a virus /trojan/ in the latest Chromium Installer /Sync • WebRTC • Widevine • 64.0.3282.140 (520840) • Saturday, 3 Feb 2018 /.
The detection shows as this:
![image](https://user-images.githubusercontent.com/12463244/35850536-d9e2d622-0b2d-11e8-8e5c-2431dd7e5144.png)

**Comment by uBlock-user** [comment]
https://github.com/henrypp/chromium/issues/33#issuecomment-353769205

**Comment by ramones79** [comment]
I figured out it's probably a false positive, but still this needs to be resolved with Avira somehow, here is why:
- Avira is one of the best and most trusted anti-virus software,
- browser software is a critical security point for every person or business. Users should be able to trust their browsers. A compromised browser is a disaster.

**Comment by uBlock-user** [comment]
Then download the .zip and see for yourself. 

No anti-virus will ever be perfect no matter how trusted it gets or which company owns it. There's nothing to resolve, that's what `false positive` means. There's no heuristic method to detect without getting any false positives.

**Comment by ramones79** [comment]
I know all of this. What I was trying to say is to notify Avira to mark it as a false detection.
I've found it myself (https://analysis.avira.com/en/submit-urls) and already submitted it as a possible false positive. Once they confirm - Avira will no longer detect it as a virus.

**Comment by uBlock-user** [comment]
That's upto Avira then, keep it in mind, lots of exes get submitted everyday, so it can take long. What I would do if I were you is add an exception until it settles.

**Comment by chrme** [comment]
it's happen time to time :smile:

**Comment by ramones79** [comment]
Sorry for forgetting to close the thread. After submitting the file for possible false-positive to Avira, the AV no longer detects any security issues.
