### ISSUE TITLE
chromiun doesnt auto update anymore

### ISSUE THREAD

**Issue by kanink007** [henrypp/chromium#36]
hello. i dont exactly know if its an issue with chromium or an issue with the chromium launcher.
today a new version was detected (v 186 in the very end). but chromium launcher doesnt download the update. 
isnt the update ready yet to download via chromium launcher?
or is chromium launcher causing a problem?

**Comment by woolyss** [comment]
This is an issue about the Chromium launcher (chrlauncher)
Please, check https://github.com/henrypp/chrlauncher/issues/95
