### ISSUE TITLE
Without SSE2 requirement?

### ISSUE THREAD

**Issue by Theowoll** [henrypp/chromium#38]
The home page says "Chromium is not available on XP and Vista since version 50. For help, version 49 works fine." Well, not on my machine. Does version 49 require SSE2? If so, could there be a hint on the home page, and ist there an older version that runs on old CPUs?

The last Chrome version that runs on my old machine is 34.0.1847.137, by the way.

**Comment by woolyss** [comment]
>  Does version 49 require SSE2?
I do not know. I tested it on Windows SP2 with all updates, few years ago. It worked. I am the admin of the site you talk about. ;)

Probably, the simplest way is to use a portable version. Test builds at https://sourceforge.net/projects/crportable/files/ and choose builds before version 50. 

Info: these builds are correct and without malware. Read https://sourceforge.net/projects/crportable/ for more. This project is dead (stopped by its author) but it is good to have a repository for old builds.

**Comment by Theowoll** [comment]
I took a closer look at the error messages and they say "Exception Information Code: 0xc000001d", which means "Illegal Instruction", apparently. I get these messages for all the browser versions that require SSE2 (Firefox > 48, Chrome > 34, Opera >20), as well for the Chromium 49 builds from https://chromium.woolyss.com/ and https://sourceforge.net/projects/crportable/. All these browsers work under the same Windows XP SP3 installation on a newer CPU.

**Comment by chrme** [comment]
The google says that the latest chromium version without sse2 support is v35.0.1866.0. The only way is to find it in the google repository because i cannot compile it (it won't compile with current OS or ms visual studio)
