### ISSUE TITLE
Doesn't Work.

### ISSUE THREAD

**Issue by duttaditya18** [henrypp/chromium#39]
When I open `chromium-sync.exe`, nothing opens up.

**Comment by devnullconsole** [comment]
It's because it's updating in the background and the message will not pop up

**Comment by duttaditya18** [comment]
@devnullconsole It is not updating anything. The process starts for a couple of seconds and then stop immediately.

**Comment by devnullconsole** [comment]
@duttaditya18 I will try it in my environment, which link did you download?

**Comment by duttaditya18** [comment]
@devnullconsole The latest release. https://github.com/henrypp/chromium/releases/latest

**Comment by chrme** [comment]
@duttaditya18 check the log file and try to fix the problem
log can be here
```c
   C:\WINDOWS\Temp\chrome_installer.log
```

or 
```c 
   C:\Users\<yourID>\AppData\Local\Temp\chrome_installer.log
```

**Comment by devnullconsole** [comment]
@duttaditya18 I have done four installation tests.
and in my environment it all ended normally.

*New installation of v68.0.3439.0-r560956-win32/chromium-sync.exe on Windows 10 1703 (for both of 32/64bit)

*New installation of v68.0.3424.0-r556419-win32/chromium-sync.exe on same environment
 Then update with v68.0.3439.0-r560956-win32/chromium-sync.exe

https://github.com/henrypp/chromium/releases/download/v68.0.3439.0-r560956-win32/chromium-sync.exe
SHA256  915B40ACFDAA7D90D1FB9169708C69C7DA120A2F0E33F06A008E570663C4E5BE

https://github.com/henrypp/chromium/releases/download/v68.0.3424.0-r556419-win32/chromium-sync.exe
SHA256  BD74C4741AE8473F917950B7D74F0504C33BA51A9475F0AFC2D2B727FAA1283D


How about your C:\Users\'username'\AppData\Local\Temp\chromium_installer.log?

**Comment by duttaditya18** [comment]
@devnullconsole So, as it turn out, the folder : `C:\Users\Aditya\AppData\Local\Chromium\` was present even though there was nothing in the folder.

Deleting that solved the problem.

Thanks for the help!
