### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by uBlock-user** [henrypp/chromium#4]

**Comment by chrme** [comment]
You can use official 32bit version, in the "chrlauncher.ini" set
```batch
ChromiumType=dev-official
```

**Comment by uBlock-user** [comment]
No, you misunderstood me. I want the one with all codecs enabled for 32 bit Windows, the one you build for 64 bit. The official channel doesn't have all codecs enabled in their 32 bit releases.

**Comment by henrypp** [comment]
@uBlock-user
if you need it you can do it... himself and share with us.
we have no money, no time and not enough disk space for do that.

**Comment by uBlock-user** [comment]
@henrypp If I could do it, I wouldn't post it here as an issue. I dont have the RAM and the tools to compile  everytime a new release is out, not to mention, I don't have the codecs. 
You have no money and yet you got time to reply and an internet connection too, so please  dont post bullshit. Not to mention, you have got time to compile 64 bit versions, so yeah you got have disk space. 

Don't bother lying to me, if you don't wanna do it, have the guts to admit that, it's that simple. Nobody's forcing you to lie about it. Lastly, there is no nothing to fix here, as this was a feature request. I installed a 64 bit version of Windows 10 Pro, so I dont need your help anymore.

/Closed.

**Comment by henrypp** [comment]
i dont care

**Comment by henrypp** [comment]
First. This build maded only by @chrme. No one helps him.

You can do yourself if you need, because build only for one platform used more than 20GB disk space. It difficult for only one.

You need to give thanks for this one not curse for that. If no one do it, i think, nobody cares about it.

**Comment by chrme** [comment]
here is [win32](https://github.com/henrypp/chromium/releases/tag/v55.0.2871.0-r420841-win32), but it's not my priority

**Comment by uBlock-user** [comment]
@chrme thanks, will you compile future release for win32 or is this a one off occurrence ?

**Comment by chrme** [comment]
yes, once in a 1-2 weeks i think it's possible
