### ISSUE TITLE
bad builds

### ISSUE THREAD

**Issue by uBlock-user** [henrypp/chromium#40]
What's with the broken dev builds @chrme ? The last 64 bit build randomly crashed and now this has broken extension popup UI - https://i.gyazo.com/9387168454758576d3301b85966a5773.png

The last good dev build was -  68.0.3424.0

After that every 64 bit dev build is having issues...

**Comment by Retia-Adolf** [comment]
broken extension popup UI +1
and when minimize and restore Chromium window, its UI become not correctly working, until I click the maximize/restore button on the right-top.

**Comment by Retia-Adolf** [comment]
This is first time I tried chrlauncher to update Chromium, not dare to do so again. 

Annoying rounded rectangle UI elements, unexpected bugs, I'm sure I need to test run next time update. So finally need manually update, sad.

Just hope developer could release a new correct revision asap, will be grateful for that.

((btw also hope Google won't apply their so-called "Material Design refresh" at the next version, that's not Material Design, that's a bunch of mad craps.

**Comment by uBlock-user** [comment]
Just go back to previous stable build until a working build is released for now..

**Comment by uBlock-user** [comment]
No longer broken extension UI like before but chrome://history is broken, won't list all websites I visited.

**Comment by uBlock-user** [comment]
Fixed, read - https://github.com/RobRich999/Chromium_Clang/issues/4#issuecomment-395198971
