### ISSUE TITLE
Unexpected crashes due to heap corruption on v67.0.3396.62-r550428-win64

### ISSUE THREAD

**Issue by CirnoT** [henrypp/chromium#41]
Release: https://github.com/henrypp/chromium/releases/tag/v67.0.3396.62-r550428-win64 exhibits unexpected crashes due to heap corruption. Observed total of 3 crashes during 6 hours time. No usage patters recognized, one was right after installation without even interacting with browser, second was when opening page from Google search, third was when watching YouTube video.

Attached below are crash logs from Event Viewer.

```
Faulting application name: chrome.exe, version: 67.0.3396.62, time stamp: 0x5b0f38bd
Faulting module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Exception code: 0xc0000374
Fault offset: 0x00000000000f4eeb
Faulting process id: 0x683c
Faulting application start time: 0x01d3fa4d55b5f2e1
Faulting application path: C:\Users\robot\AppData\Local\Chromium\Application\chrome.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 6a5a3533-5dba-4d5e-ba83-c201e619942b
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: chrome.exe, version: 67.0.3396.62, time stamp: 0x5b0f38bd
Faulting module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Exception code: 0xc0000374
Fault offset: 0x00000000000f4eeb
Faulting process id: 0x28a0
Faulting application start time: 0x01d3fa4b9e2df8fb
Faulting application path: C:\Users\robot\AppData\Local\Chromium\Application\chrome.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: a2c8878d-f8f1-4347-b7ff-9122d91ae316
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: chrome.exe, version: 67.0.3396.62, time stamp: 0x5b0f38bd
Faulting module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Exception code: 0xc0000374
Fault offset: 0x00000000000f4eeb
Faulting process id: 0x435c
Faulting application start time: 0x01d3fa4b8b049d6a
Faulting application path: C:\Users\robot\AppData\Local\Chromium\Application\chrome.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: c5cc7e11-c60c-429c-910e-60e670ee0b15
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by uBlock-user** [comment]
another batch of bad builds, happened to me on previous 64 bit dev build.

**Comment by eider96** [comment]
```
Faulting application name: chrome.exe, version: 67.0.3396.62, time stamp: 0x5b140530
Faulting module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Exception code: 0xc0000374
Fault offset: 0x00000000000f4eeb
Faulting process id: 0x25d8
Faulting application start time: 0x01d3fb82260fffee
Faulting application path: C:\Users\robot\AppData\Local\Chromium\Application\chrome.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 37594763-c634-41e5-b015-9a0b43e2f5c0
Faulting package full name: 
Faulting package-relative application ID: 
```

Happened while not doing anything. Are you interested in .dmp file?

**Comment by RobRich999** [comment]
Seemingly random heap corruption popped up in some of my builds last month, and looking at my comments over at Jerry's site, it was present through at least 68.0.3436.0.

I never found the actual underlying cause, though I can say it was eventually resolved in the trunk. AFAIK, I have not seen any heap corruption crashes in the past couple of weeks.

**Comment by grasmanek94** [comment]
I think I got the same crash:

```
G, [05.06.18 19:36]
Faulting application name: chrome.exe, version: 67.0.3396.62, time stamp: 0x5b140530
Faulting module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Exception code: 0xc0000374
Fault offset: 0x00000000000f4eeb
Faulting process id: 0x29f8
Faulting application start time: 0x01d3fcf3a6a72623
Faulting application path: C:\Users\Rafal\AppData\Local\Chromium\Application\chrome.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 6d66dd71-c80f-41d0-af9e-fc1f0ec01389
Faulting package full name: 
Faulting package-relative application ID:
```


when visited (in order), reddit, facebook..
tried to open new tab on second monitor (+, then drag new tab to other monitor, then focus url bar).

then after relaunch
immediately again:
```
Faulting application name: chrome.exe, version: 67.0.3396.62, time stamp: 0x5b140530
Faulting module name: ntdll.dll, version: 10.0.17134.1, time stamp: 0x207580e2
Exception code: 0xc0000374
Fault offset: 0x00000000000f4eeb
Faulting process id: 0x36c4
Faulting application start time: 0x01d3fcf151b53387
Faulting application path: C:\Users\Rafal\AppData\Local\Chromium\Application\chrome.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 0527abb8-731c-4101-8855-51740eee2598
Faulting package full name: 
Faulting package-relative application ID:
```
Windows 1807 build.

**Comment by chrme** [comment]
i can upload a pdb for v67.0.3396.79, which file do you need exactly?

**Comment by CirnoT** [comment]
No crashes so far on 67.0.3396.79 so that would be pointless for now, but chrome.dll is the only one needed. Will keep issue open for next few days and if no crashes occur in that period I'll close it as solved.

**Comment by chrme** [comment]
got it

**Comment by uBlock-user** [comment]
> No crashes so far on 67.0.3396.79

That's because it's the official stable version.

**Comment by CirnoT** [comment]
>That's because it's the official stable version.
Please elaborate how that's different from 67.0.3396.62

**Comment by uBlock-user** [comment]
The left out regression bugs got patched in the subsequent release, ofcourse you won't find any mention of that there.

**Comment by CirnoT** [comment]
That's not the point I was making. Previous release was 'official stable' too as far as I'm aware. Whether subsequent one fixed regressions is irrelevant to this discussion. Either way, no reason to steer offtopic.

No crashes so far so I think I can safely close it. Will open new issue if it ever resurfaces.

**Comment by uBlock-user** [comment]
You asked how it's different from the previous stable release and I answered it exactly in the very first line, that's all. Stable builds don't have any such regressions in the first place and but if they did, they get patched in the subsequent releases, that's why Chromium team has rapid release schedule in the first place.
