### ISSUE TITLE
canPlayType method returns undefined for HEVC

### ISSUE THREAD

**Issue by truedread** [henrypp/chromium#42]
```javascript
var obj = document.createElement('video');
console.log(obj.canPlayType('video/mp4; codecs="hev1.1.6.L93.B0"'));
```

This snippet of code returns undefined, meaning that playing HEVC through MSE rather than direct play is impossible. Perhaps compiling chromium with [this line](https://github.com/chromium/chromium/blob/master/content/browser/media/media_canplaytype_browsertest.cc#L52) set to `kPropProbably` or `kProbably` would fix it?

**Comment by chrme** [comment]
it doesn't work, i try it

**Comment by truedread** [comment]
Very odd. Do you think there's any way you could get this working in your builds of Chromium? The only reason HEVC videos even play on your builds is because the direct play videos have mimeTypes of video/mp4. If the codec were included in the mimeType, which is the normal convention, the playback would fail. Since the codec isn't required for direct play, it poses no problem, but for MSE and MPEG-DASH playback, the codec is required and thus your builds fail when playing HEVC content. If there's any way you could get this working it would be much appreciated!

**Comment by chrme** [comment]
I'm only compiling ffmpeg module with h264 and hevc codecs, i don't touch the chromium base code and don't know how to do what you request :confused:

**Comment by truedread** [comment]
Well, I figured it out. I compiled my version of Chromium and modded the `MimeUtil` class to force it to support HEVC. On [this](https://github.com/chromium/chromium/blob/master/media/base/mime_util_internal.cc#L939) blank line I added the following code:

```cpp
if (video_codec == kCodecHEVC) {
#if BUILDFLAG(ENABLE_HEVC_DEMUXING)
  return IsSupported;
#else
  return IsNotSupported;
#endif // BUILDFLAG(ENABLE_HEVC_DEMUXING)
}
```

This code snippet checks if the video codec is HEVC, and if so check if the build flag `enable_hevc_demuxing` is set to true. If it is, HEVC is supported. If it isn't, HEVC is not supported. The previous method of checking if HEVC was supported or not was to create a new `MediaClient` object and see if that supports HEVC decoding. Since HEVC decoding isn't supported, it will always return `IsNotSupported` even if FFmpeg can decode it. With this mod, it should disregard the media client and just check based off of build arguments.

**Comment by chrme** [comment]
i will try it with a next build

**Comment by truedread** [comment]
Just downloaded the latest build, seems to work! Thanks! Could you update `hevc_support_new.md` with my instructions so that people following it compile it with MSE support? Thanks again!

**Comment by chrme** [comment]
That's good to know.
I've updated the instruction.

**Comment by truedread** [comment]
Nice, the issue seems to be fixed, closing.

**Comment by candiesdoodle** [comment]
Hello,

This code to be added to "src/media/base/mime_util_internal.cc" doesnt seem to work any more.

`if (video_codec == kCodecHEVC) {
#if BUILDFLAG(ENABLE_HEVC_DEMUXING)
  return IsSupported;
#else
  return IsNotSupported;
#endif
}`

It throws a buildflag error. And adding `enable_hevc_demuxing` doesnt work either. any suggestions?
