### ISSUE TITLE
apps-gallery-update-url

### ISSUE THREAD

**Issue by shadowtime** [henrypp/chromium#43]
Have an issue with "--apps-gallery-update-url" command line switch. The chromium terminates when I set apps to install on first run (default_apps\external_extensions.json) and launch with "--apps-gallery-update-url=localhost" switch.

**Comment by chrme** [comment]
I don't even know what this flag is, but recent build doesn't have this problem as i checked it.

**Comment by shadowtime** [comment]
The problem was Adobe Reader DC Extension. When I run with that flag the old Adobe Reader DC extension that was self added to a browser has caused termination. After uninstall Adobe Reader DC problem has been solved.

**Comment by chrme** [comment]
Ah, got it.
