### ISSUE TITLE
Only installable for one user.

### ISSUE THREAD

**Issue by tlhonmey** [henrypp/chromium#44]
When I install this, it enters itself into the list of installed applications, but installs its files into the home directory of the user doing the installation with no access permitted by other users.

If I subsequently try to install it into another user's account it seems to see that it's already installed on the system and does nothing (Maybe it triggers an update of what's in the original user's account, I'm not sure.)

So effectively Chromium can only be installed for one user account.

It would be nice if it could be adjusted one way or another and do either a true system-wide installation and be accessible for everyone, or a true single-user installation and not cruft up the global applications list in a way that makes it not installable for other user accounts.

**Comment by uBlock-user** [comment]
Use the portable version in the .zip.

**Comment by tlhonmey** [comment]
That may be a usable tactic in my case, I'll give it a try and see what happens.

Globally installing an application in a way that makes it only usable by one account is still bad form though...

**Comment by uBlock-user** [comment]
You can blame Chromium devs for that. Portable version doesn't come with installer, so unzip and put the package in whichever drive you want and no user account restrictions either.

**Comment by Unixware** [comment]
latest build does not even run, WTF

**Comment by chrme** [comment]
which one exactly?

**Comment by chrme** [comment]
yesterday I accidentally delete this release and now it's restored, try again..

**Comment by Unixware** [comment]
ok thx works well now

**Comment by Anonymphous** [comment]
Hello @chrme , will there be a stable-nosync release in the near future?
