### ISSUE TITLE
Virus detected in multi packages (exe & zip).

### ISSUE THREAD

**Issue by joeshae** [henrypp/chromium#45]
If you input the download URL of package into virustotal.com, it shows no virus detected. 
But If you download the same package to local (especially for 32-bit package), and then upload it to virustotal.com, virus will be detected.
And, most of the anti-virus software will alert virus detected when package is stored locally.
It's really weird!

For example:

Input the URL "https://github.com/henrypp/chromium/releases/download/v68.0.3440.84-r561733-win32/chromium-sync.exe" into virustotal.com, it shows no virus detected:
https://www.virustotal.com/#/url/f987795ae92ca6b60eb7426ce169ca4448fbfedba482e956c676c7940a6a7cc4/detection

And I download the package chromium-sync.exe from this URL to local computer,  then upload it to virustotal.com: Virus detected!
https://www.virustotal.com/#/file/28a64bf36cfa18e323e8a01de93bde3dbca241665554563f7ccf0951c75337fe/detection

And the anti-virus software installed on my local compute will alert the same virus warning.

Do you know what's wrong with it? And how to resolve this issue?

Thank you!

**Comment by uBlock-user** [comment]
False positive, use the portable .zip if you feel uncomfortable still.
