### ISSUE TITLE
Sync isn't working on 68.0.3440.106 (stable)

### ISSUE THREAD

**Issue by AzimsTech** [henrypp/chromium#46]
I keep getting this message on latest chromium stable (Nik) build Win64

<img src="https://i.imgur.com/q15s3Ge.png">

**Comment by uBlock-user** [comment]
Not an issue. Check your sign-in credentials details, doesn't happen on my end.

https://www.google.com/search?source=hp&ei=qlFxW-7GMYm99QOT3p6ICw&q=sign-in+details+are+out+of+date&oq=Sign-in+details&gs_l=psy-ab.3.0.0j0i22i30k1l9.788.4126.0.5396.16.14.0.1.1.0.185.1462.0j10.10.0....0...1c.1.64.psy-ab..5.11.1477.0..35i39k1j0i131k1j0i22i10i30k1.0.WcrZAri5c28
