### ISSUE TITLE
Req: No "DNS Proof Fetching" version

### ISSUE THREAD

**Issue by rugabunda** [henrypp/chromium#47]
Chromium has implemented **DNS Proof Fetching** which introduces one of the greatest privacy concerns the international community has ever seen. The new DNS queries begin after the installing the latest Chromium v69.0.3497.81-r576753-win64 (stable). AuditProofQuery basically sends a clone of every dns query to ct.googleapis.com upon each https request, but its implications go much further than that. Please review the privacy concerns and consider releasing a version of chromium which removes the new **Certificate Transparancy DNS-based protocol**, [AuditProofQuery](https://github.com/chromium/chromium/search?q=AuditProofQuery&unscoped_q=AuditProofQuery).

Privacy implications of Certificate Transparency’s DNS-based protocol 
https://docs.google.com/document/d/1DY2OsrSJDzlRHY68EX1OwQ3sBIbvMrapQxvANrOE8zM/edit#
https://www.agwa.name/blog/post/how_will_certificate_transparency_logs_be_audited_in_practice
https://www.symantec.com/connect/blogs/privacy-redaction-and-certificate-transparency
https://groups.google.com/forum/#!topic/certificate-transparency-chrome/X1ja-E8FsUI

Privacy Concerns:
1. **Requesting an inclusion proof leaks each and every https visited domain to the client software supplier in realtime, that being Google, even for Chromium users; This gives Google droves of data once only accessible to the users ISP, and consolidates further the American companies monopoly on international population surfing data, statistics, & demographics.  Chrome now leaks sensitive cached hosts and certificate hashes not obtained publicly or by a DNS resolver, including IP to IP, IP to router, SQL and any other remote & local servers accessed through a Chrome browser... potentially mapping sensitive global server infrastructure.
2. Cross-resolver leakage (Leaking after enabling/disabling VPN/TOR, or switching DNS services)
3. Leakage of client information via edns-client-subnet
4. Realtime Disclosure of **actual visited hosts vs only resolved hosts** [previously only known by ISP]
5. Realtime Disclosure for hosts whose address was not obtained via DNS lookup [direct connection via ip]
6. Local authoritative resolver leakage**

According to symantec: 

> In my previous blog, I discussed the need to balance the benefits of logging certificates publicly with the need of many customers to prevent logging of internal domain names they consider private.
> 
> The Internet Engineering Task Force (IETF) also recognized the importance of this, and has made solid progress in support for name redaction in the latest version of the Certificate Transparency (CT) specification. Based on this progress, Symantec will soon be adding a “redaction” option for customers to exclude publishing of sub-domain information when requesting certificates. With this feature, customers will be able to get the full benefits of monitoring certificates issued by Symantec and also get the privacy protection they need.
> 
> Google – whose browser is currently the only major one to support Certificate Transparency - has not yet announced when or whether Chrome will accommodate redaction. As a result, it is possible that Chrome will show an “untrusted” warning if it encounters certificates where customers have chosen to log their certificates with redacted sub-domain information. Therefore, customers who have internal, browser-based applications, where privacy of certificate domain information is important, may want to consider using an alternate browser or one of our Private CA options.
> 

Mitigation? Remove it from Chrome source code. Until then Block ct.googleapis.com; This can only be done with wildcard/subdomain supported resolves like dnsmasq dnscrypt, and Acrylic DNS Proxy. Given the unique inclusion hash in the dns subdomain, this cannot be blocked in a windows hosts file.

example:
30FGZEPP37IXHWODTSZV4YF75QDZI36U7KG73WHCWMYH3FZGHEKZ.hash.icarus.ct.googleapis.com

Recommended: block it nation wide.

Thank you!

**Comment by uBlock-user** [comment]
This won't happen if DNSCrypt is used.

**Comment by rugabunda** [comment]
This is the exact version of Chromium I am using, this is what I am seeing.

[](https://image.ibb.co/mdLAC9/Chrome_Pretech.png)
[dnsmasq.log](https://github.com/henrypp/chromium/files/2364803/dnsmasq.log)

**Comment by rugabunda** [comment]
https://image.ibb.co/mdLAC9/Chrome_Pretech.png

**Comment by uBlock-user** [comment]
> This is what I am seeing while using dnscrypt.

Nothing there shows any connections made by Chrome and data being sent to Google's servers, you should look at `chrome://net-internals/`

> Does Google really care about your security? Blah Blah Blah...

Now you just went completely off-topic, but I wil say this once. By that logic, you should stop using Android devices too, but you won't or iphone if you're into that. those devices smuggle more than a browser would ever do.

**Comment by rugabunda** [comment]
Incorrect, I use a custom DNS server.

Looking at the pictures and in the dnsmasq log I have provided, as well as the links, you will see Chrome's fetch inclusion proofs over DNS. Instead of making an HTTP request to the get-proof-by-hash endpoint, Chrome makes a series of DNS requests for sub-domains of ct.googleapis.com which contain the parameters of the inclusion proof request (e.g. D4S6DSV2J743QJZEQMH4UYHEYK7KRQ5JIQOCPMFUHZVJNFGHXACA.hash.pilot.ct.googleapis.com). The name servers for ct.googleapis.com respond with the inclusion proof inside TXT records.

All of these requests are operating souly from within chrome itself and the source code governing the LogDnsClient.

**Comment by uBlock-user** [comment]
> Chrome makes a series of DNS requests for sub-domains of ct.googleapis.com which contain the parameters of the inclusion proof request (e.g. D4S6DSV2J743QJZEQMH4UYHEYK7KRQ5JIQOCPMFUHZVJNFGHXACA.hash.pilot.ct.googleapis.com).

and yet that doesn't match with your claim that data is collected and then sent to Google's servers in droves and from the picture that's only two not series of requests, that also over dns protocol. If you have issue with that, then you shouldn't be using Google services at all because this is one of the many things google does, removing this doesn't end the data collection that claim here.

> henrypp releases modified versions of chromium

Wrong again, he doesn't. a guy named @chrme aka nik does. Also https://chromium.woolyss.com/ is not owned or ran by henrypp, Jerry is the owner.

> questionable and privacy reducing components like Widevine, Sync, and WebRTC removed

Nothing's quesitonal about that, he doesn't remove them either, they were disabled before. Now Sync/WebRTC is no longer disabled anymore Widewine is not a privacy component, you're just showing your tin foil hat.

**Comment by rugabunda** [comment]
Here it can be seen in chromium directly, as you can see, I am blocking these querys at the router level. You can also do this using simple dnscrypt in windows, or in dnsmasq in linux. 
https://image.ibb.co/j6tJkU/Proof.png

**Comment by rugabunda** [comment]
For whatever reason, bumping up to Version 69.0.3497.92 (official) and 71.0.3551.0 stopped these querys. They were only occuring in henrypp's 69.0.3497.92 (576753) • Tuesday, 11 Sep 2018; not sure what is going on there, maybe a test run?

**Comment by chrme** [comment]
maybe a test, or maybe it was a mistake..
ps. henrypp doesn't do chromium builds, i'm only using his repo :smiley:
