### ISSUE TITLE
Old style of the New Tab page can't be enabled in Chromium 69 via flags

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [henrypp/chromium#48]
Version 69 introduced a major UI redesign, and it currently has flags that can be used to re-enable old UI.

My current settings:
chrome://flags/#top-chrome-md - Normal
chrome://flags/#use-google-local-ntp - Enabled
chrome://flags/#ntp-icons - Disabled
chrome://flags/#ntp-ui-md - Disabled
chrome://flags/#secondary-ui-md - Disabled

With these flags everything looks like it used to look in v68, except for the New Tab page - it still displays small circular icons instead of the webpage previews.

According to https://old.reddit.com/r/chrome/comments/9dt60q/ , it's possible to enable old style of the New Tab page in Google Chrome v69 with these flags, but it seems like something doesn't work in this build of Chromium 69.0.3497.81.

**Comment by nbmrjuhneibkr** [comment]
Thanks, that worked. I'll close the issue now.
Although I'm still not sure why these flags were never mentioned in regards to Google Chrome. Perhaps they're only needed in Chromium?

**Comment by uBlock-user** [comment]
Use them as they long as they last, Google may remove them anytime they like.

**Comment by nbmrjuhneibkr** [comment]
They'll probably remove flags that affect overall UI style, but leave the ones only affecting NTP.
I've been using chrome://flags/#enable-ntp-remote-suggestions on Android for a very long time, and it's still available.

**Comment by uBlock-user** [comment]
`chrome://flags/#one-google-bar-on-local-ntp` has been removed in Chromium 70, so other such NTP flags may get the axe soon, this is why i stick to default for the most part, can't say when they will get removed.
