### ISSUE TITLE
Saying "No" to material design

### ISSUE THREAD

**Issue by rmsEfx** [henrypp/chromium#5]
Looks like v55.0.2868.0 puts "material design" as a default style with no turnig off by flags and etc. So, maybe anyone knows what version goes without "md" as a default... ? (ver. 55.0.2865 still able to turn off)

**Comment by chrme** [comment]
here the commit https://chromium.googlesource.com/chromium/src/+/55703dc - it's v55.0.2867.0
before this commit you can turn it off

**Comment by rmsEfx** [comment]
Thanks for the answer .. If anyone will have a time and knowledge to compile last non-material design build, it will be useful for the users ...

Link (http://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/419802/) is ready build with all syncs, webrtc'es and other stuff from Chromium authors.

**Comment by chrme** [comment]
[here you go](https://github.com/henrypp/chromium/releases/tag/v55.0.2867.0-r419802-win64)

**Comment by rmsEfx** [comment]
Thank you!!!!!

**Comment by henrypp** [comment]
you can disable material design on chrome://flags page

chrome://flags/#enable-md-history
chrome://flags/#enable-md-settings

**Comment by uBlock-user** [comment]
> you can disable material design on chrome://flags page

chrome://flags/#enable-md-history
chrome://flags/#enable-md-settings
chrome://flags/#show-material-design-user-menu

Hello, I did that and the material design is still there. It doesn't go back to old design.

Chromium version - 56.0.2890.0

**Comment by henrypp** [comment]
@uBlock-user switch off this settings and it only available in latest build which can disable material design on settings/history pages only, so sad(

**Comment by uBlock-user** [comment]
@henrypp what do you mean by switch off ? I disabled all those settings, but the material design is still there. It cannot be reverted back to old design.  I have the latest build, you cannot disable material design, simple. I dont want to disable it on settings or history pages, I want the old design back and I cannot get it back which sucks donkey balls! Fuck the development team of Chromium, they messed it up!
