### ISSUE TITLE
Command line proxy settings seem to be ignored.

### ISSUE THREAD

**Issue by Derkades** [henrypp/chromium#50]
This works fine on Chromium Portable from portableapps.com. I created a shortcut, went to properties and added --proxy-server="socks5://127.0.0.1:1080" (the proxy server doesn't actually exist, but that shouldn't matter).

On the portableapps version, `chrome://version` looks like this (note that the flags are present)
![image](https://user-images.githubusercontent.com/15892014/45516592-dbd10780-b7ab-11e8-9e7f-4b80fcafd27e.png)

On chromium-sync portable, it looks like this:
![image](https://user-images.githubusercontent.com/15892014/45516693-39fdea80-b7ac-11e8-8aaa-e2e2589ab932.png)

**Comment by chrme** [comment]
@Derkades because for chlauncher you need to edit chrlauncher.ini (append the socks to the option "ChromiumCommandLine")

**Comment by Derkades** [comment]
Thanks
