### ISSUE TITLE
Aliasing effect/distortion with YouTube videos

### ISSUE THREAD

**Issue by markojurkovic** [henrypp/chromium#51]
I've noticed a strange issue with these builds of Chromium. When playing HTML5 videos, on YouTube for example, there is an aliasing (distortion) effect going on, which is most clearly noticeable on text in videos.  The same effect does **not** happen with the stable Google Chrome (I tested with the latest "stable" version of both browsers, that is, version 69.0.3497.100). I also tried the latest dev version of Chromium, and the issue also appeared.

On the screenshots attached to this post, the effect is clearly visible in the text on the right hand side of the video frame and the ticker text at the bottom. The video used to take the screenshots was played at 720p resolution on YouTube in both cases. I believe this issue might have something to do with the flags or video codecs used in the build process, which is causing what appears to be a video scaling distortion.

The first screenshot represents the Google Chrome build, and the second represents Chromium.

![chrome](https://user-images.githubusercontent.com/9203900/45725492-630ee880-bbbb-11e8-9c00-d08b29f802c2.png)
![chromium](https://user-images.githubusercontent.com/9203900/45725493-63a77f00-bbbb-11e8-8a6c-f4ee7e49f969.png)

**Comment by chrme** [comment]
strange... because i don't have this problem on my side (nvidia card)

**Comment by markojurkovic** [comment]
Yes, I forgot to mention that I'm using Intel graphics. I also tried reverting to an older graphics driver version. No difference.

**Comment by uBlock-user** [comment]
Disable `Use hardware acceleration when available` in Chromium and check it still happens.

**Comment by markojurkovic** [comment]
> Disable _Use hardware acceleration when available_ in Chromium and check it still happens.

Yup, if I turn off hardware acceleration, the issue does not happen.
