### ISSUE TITLE
[Solved - see Tags, not Releases] Please build Chromium 54 with sync and codecs!

### ISSUE THREAD

**Issue by Darthagnon** [henrypp/chromium#54]
Dear Sir,

I was wondering if it would be possible for you to build Chromium v54.0.2840 with sync enabled, Google API keys and the extra codecs for x86 and x64 Windows? 

It's the best version I've found, as it supports both Material v1 and Material v2 user interfaces (I can't stand the current Material v3 UI in Chrome 70). As far as I know, v54.0.2840 is the last version to support the flags that fully disable Material Design in Chromium, which is what I'm seeking.

Version 54.0.2840 (last stable v54 Chromium supporting disabling Material v2 flags, afaik, unless you know better?) can be downloaded from: (the binaries available, however, lack API keys and the extra codecs - Iridium v54 is the current best alternative, as it includes the codecs, but lacks sync and various Google-specific features like translate)

(x86)
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/414638/
(x64)
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/414635/

**Comment by chrme** [comment]
no, it's not possible now with vs2017, you need old version of visual studio but i don't have it anymore

ps: or you can find v54 here https://github.com/henrypp/chromium/tags

**Comment by Darthagnon** [comment]
@chrme, a major Thank You for that link! I had looked through "Releases" before and hadn't found v54. Following the link you gave, I found v54. Thank you so much!

**Comment by Darthagnon** [comment]
Whoa, just realised that this was issue #54 asking for Chromium v54. Talk about coincidence :D

**Comment by chrme** [comment]
@Darthagnon :smile: 
@alexipavlenko i'm not henry, but iirc the ungoogled build was without webrtc.
