### ISSUE TITLE
Any chance of upgrading chromium dev to v75?

### ISSUE THREAD

**Issue by pitsi** [henrypp/chromium#55]
Hi!

I regularly check chromium.woolyss.com for new your builds of chromium, mainly the dev ones. For the past couple of days, I noticed that there was a warning, in red, next to your build, as seen here

![2019-03-25-100135_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/54903880-9a9d7b00-4ee5-11e9-8e9d-eef0248cfac6.png)

And today I see that the warning is missing, along with the entire entry for your dev build! Will you update it anytime soon? I know that building chromium is a really time consuming task because I have seen the build times of the chromium packages here in debian that now count in DAYS.

I would install the stable version of your builds, but I think that chromium profiles are not backwards compatible, so I would have to set itup again from scratch.

Thank you in advance.

**Comment by chrme** [comment]
@pitsi Hello! I mainly focused on building the stable release (because i use it by myself). For the dev build i'm currently don't have a time, fulltime job. But there is another dev's who build the lkgr branch and you can download it, i.e. [THIS](https://chromium.woolyss.com/#win64-dev-marmaduke)

**Comment by pitsi** [comment]
I see. Thank you for the info :)
I will probably get marmaduke's build now, since I can not "downgrade" to a stable build and keep yours.
