### ISSUE TITLE
Screen sharing in Hangouts not working

### ISSUE THREAD

**Issue by bladeSk** [henrypp/chromium#6]
Hi Nik, thanks for making these builds. I've recently discovered one flaw that prevents Google Hangouts screen sharing from working. It affects both LKGR and Stable builds.

After a bit of googling, this seems to be the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=413942
Specifically, Chromium needs to be built with `enable_hangout_services_extension=1` to make this work.

**Comment by chrme** [comment]
try [THIS](https://github.com/henrypp/chromium/releases/tag/v56.0.2884.0-r424037-win64) v56 SYNC, i've include enable_hangout_services_extension in config

**Comment by bladeSk** [comment]
Perfect, it's working now, thanks!
