### ISSUE TITLE
can not decode h265

### ISSUE THREAD

**Issue by liuyijuna** [henrypp/chromium#8]
Hi, henrypp,
I followed the instructions in file building_chromium_gn.md to build chromium, compile succeeded, but I still can not play h265 files, the file is mp4(H265 + AAC), it only can play audio, but can not play video; It can play H264 file, will you tell me how to compile chromium with h265 codec ?
 thanks a lot!!

**Comment by chrme** [comment]
try [this guide](https://github.com/henrypp/chromium/blob/master/hevc_support.md)

**Comment by uBlock-user** [comment]
You did something wrong or missed something.

Test it here - http://www.h265files.com/embed-h265-video.php

**Comment by liuyijuna** [comment]
It worked, H265 can be decoded using this guide, thanks for your reply and guide, best wishes.
