### ISSUE TITLE
Chromium flickering around

### ISSUE THREAD

**Issue by Phoenix1747** [henrypp/chromium#9]
This is a copied issue, originally from https://github.com/henrypp/chrlauncher/issues/39 because it does suit Chromium itself better than crlauncher.
---

This is extremely annoying: I am using crlauncher with dev-codes-sync on Windows 10.

Every so often chromium dissapears to show up after like half a second. That looks like flickering and is extremely annoying, because it sometimes kills a video or eg. a pdf document which i was reading.

**Comment by chrme** [comment]
can you check it with my stable-codecs-sync and tell how it goes? and which GPU card do you have? also try to disable hardware acceleration in settings?

**Comment by Phoenix1747** [comment]
Disabling hardware acceleration worked for me, thanks! Don't know why but yeah.

- dev-codecs-sync: 64-bit | Windows 10: 64-bit + GTX 750 Ti
